    FROM node:18 AS build

    WORKDIR /app
    
    COPY ./package*.json ./
    RUN npm install
    
    COPY . .
    RUN npm run build
    
    
    FROM node:18-alpine AS production
    
    RUN npm install -g serve
    WORKDIR /app
    COPY --from=build /app/build ./build
    
    CMD ["serve", "-s", "build", "-l", "3000"]